### ISSUE TITLE
Vytvořit nový pojem v OG tam, kde uživatel klikl, místo vlevo nahoře

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#122]
# Popis
Pokud v OG vložím pojem přes pravé kliknutí na canvas, pojem je vložen na 0,0 (vlevo nahoře) - což je matoucí. Očekával bych, že bude vložen tam, kde uživatel klikl.

# Využití
Přidávání pojmů v OG.

# Užitečnost
Bylo by hezké ji mít, ale bez problémů se bez ní obejdu

**Comment by bindeali** [comment]
Zavírám, jelikož je issue dávno vyřešen.
