### ISSUE TITLE
Export pro účely RPP

### ISSUE THREAD

**Issue by trusinas** [datagov-cz/sgov-assembly-line#129]
# Popis
Výrobní lince chybí možnost vytvořený koncptuální model vyexportovat pro účely evidence údajů v RPP.

# Využití
Jedním z důvodů, proč používat výrobní linku, je povinnost zaevidovat údaje vedené v agendě do RPP. Výsledkem by měl být seznam jako např. na slidu https://docs.google.com/presentation/d/1Imr18zBgSrgR-uvv9CD_DWX3_qyMaR79_P_fCvXb_tY/edit#slide=id.g1494cb7098d_0_873
Jaká bude reálná podoba exportu (textový soubor, excel atd.) je jedno. Providla pro převod modelu na logiku evidence v RPP obsahuje metodika, s. 32 a následující.
RPP možnost importu údajů neumožňuje, ale převod diagramu na strukturu, v jaké jsou údaje v RPP evidovány, proces evidence zrychlí.

# Užitečnost
Evidenci údajů bez navrhované funcionality lze provést, ale je zbytečně zdouhavá. Nicméně bez dané funkcionality lze obtížně přesvědčovat úředníky/úřednice, aby výrobní linku používali, pokud je jejich cílem evidence údajů v agendě v RPP.

**Comment by bindeali** [comment]
Shrnutí dosavadního stavu: Export byl implementován do testovacího prostředí s [tímto OG commitem](https://github.com/opendata-mvcr/ontoGrapher/commit/8adafe0fa7814bbdc23f9cfb04664833fd231b04). Zpětná vazba je následující: 
```
Dobrý den,
 
pro účely testování exportu do RPP jsem vytvořil diagram https://slovník-test.mvcr.gov.cz/modelujeme/projects/instance-121990092.
Zkoušel jsem exportovat a narazil jsem na chyby:
do exportu CSV i TXT jde jiný diagram než aktuálně otevřený
syntaxe CSV souboru je nejednotná: názvy sloupců nejsou v „", ale jednotlivé hodnoty ano
Můžete se na to prosím podívat?
```

**Comment by bindeali** [comment]
Chyby byly opravené přes https://github.com/opendata-mvcr/ontoGrapher/pull/480.

**Comment by trusinas** [comment]
1) Můžete prosím zkontrolovat odřádkování? Zkoušel jsem na Win i Linux a je to vše na jednom řádku. Platí pro export do CSV i TXT.
2) Při exportu do TXT se vytváří soubor bez přípony ".txt".

**Comment by trusinas** [comment]
Díky předchozí chyby byly opraveny, takže jsem mohl provést text exportu jako takového. Pro tyto účely jsem vytvořil jednoduchý model - https://slovník-test.mvcr.gov.cz/modelujeme/projects/instance-121990092.
Dle modelu bych čekal následující strukturu 
1) TXT
- Typ subjektu
	 - vlastnost subjektu 03
	 - vlastnost subjektu 02
	 - vlastnost subjektu 01
	 - jednoduchá událost
	 - agendový číselník

- událost s vlastnostmi
	 - vlastnost události 01
	 - vlastnost události 02
	 - týká se

- Typ role
	 - vlastnost role 01
	 - vlastnost role 02
	 - má vazbu na

- má vazbu s vlastnostmi
	 - vlastnost vazby 01
	 - vlastnost vazby 02
	 - má vztažený prvek 1
	 - má vztažený prvek 2

- Role 2

2) CSV

Subjekt/objekt | Popis subjektu | Právní předpis (vč. ustanovení) | Údaj | Popis údaje | Právní předpis (vč. ustanovení) | Typ
-- | -- | -- | -- | -- | -- | --
Typ subjektu | Typ subjektu - definice | Typ subjektu - zdroj |   |   |   | Typ objektu
Typ subjektu |   |   | vlastnost subjektu 03 |   |   | Typ vlastnosti
Typ subjektu |   |   | vlastnost subjektu 02 |   |   | Typ vlastnosti
Typ subjektu |   |   | vlastnost subjektu 01 | vlastnost subjektu 01 - definice | vlastnost subjektu 01 - zdroj | Typ vlastnosti
Typ subjektu |   |   | jednoduchá událost |   |   | Typ události
Typ subjektu |   |   | agendový číselník |   |   | Typ objektu ?
událost s vlastnostmi |   |   |   |   |   | Typ události
událost s vlastnostmi |   |   | vlastnost události 01 |   |   | Typ vlastnosti
událost s vlastnostmi |   |   | vlastnost události 02 |   |   | Typ vlastnosti
událost s vlastnostmi |   |   | týká se |   |   | Typ vztahu

Typ role |   |   |   |   |   | Typ objektu
Typ role |   |   | vlastnost role 01 |   |   | Typ vlastnosti
Typ role |   |   | vlastnost role 01 |   |   | Typ vlastnosti
Typ role |   |   | má vazbu na |   |   | Typ vztahu

má vazbu s vlastnostmi |   |   |   |   |   | Typ vztahu

má vazbu s vlastnostmi |   |   | vlastnost vazby 01 | vlastnost vazby 01 - definice | vlastnost vazby 01 - zdroj | Typ vlastnosti
má vazbu s vlastnostmi |   |   | vlastnost vazby 02 |   |   | Typ vlastnosti
má vazbu s vlastnostmi |   |   | má vztažený prvek 1 |   |   | ?
má vazbu s vlastnostmi |   |   | má vztažený prvek 2 |   |   | ?
Role 2 |   |   |   |   |   | Typ objektu


Ke stávající implementaci mám následující připomínky
Obecně:
- nezohledňuje se číselník dle metodiky (případně prosím o specifikaci, z jakého objektu má být konkrétní číselník specializován)
- nezohledňuje vztahy s vlastnostmi
- je nutné dořešit, jak se bude přavádět událost, pokud má vlastnosti

V případě, že typ události má vlastnosti, je k diskuzi, zda by se neměl modelovat jako typ objektu, potom by export fungoval správně (a analogicky typ vztahu s vlastnostmi).

Nelze otestovat export pro typ:
•	fáze
•	činnost
protože daný typ nelze nastavit.

K CSV
- upravit generování zdroje, aby pro daný typ zobrazoval správný zdroj
- doplnit generování definice (a rozlišovat dle typu)
- ve sloupci Subjekt/objekt opakovat název pro každou vlastnost, aby bylo zřejmé, do jakého subjektu/objektu patří.

**Comment by MichalMed** [comment]
Ne všem vašim připoínkám rozumím. Potřeboval bych tedy iupřesnění . Týká se to předvším: 
* nezohledňuje se číselník dle metodiky (případně prosím o specifikaci, z jakého objektu má být konkrétní číselník specializován) 
                    - _to, že se jedná o číselník se dá poznat jedině tak, že by se kontrolovaly třídy, které jsou instancemi jedné_ konkrétní třídy, a to číselníku. To je za prvé složité implementačně a za druhé by to výrazně zvýšilo odezvu serveru. Zajímalo by mě, jakého usecasu se to týká a jak moc je to důležité?
* je nutné dořešit, jak se bude přavádět událost, pokud má vlastnosti 
                     - _tomu nerozumím, z pohledu RPP je typ události to samé jako typ objektu, nezávisle na tom, jestli má nebo nemá vlastnosti. Rozdíl mezi typem objektu a typem události je v tom, že událost se nemůže měnit, zatímco objekty ano. Jaký konktrétní případ máte na mysli?_
* Nelze otestovat export pro typ:
                • fáze
                • činnost
                     _- z pohledu modelování ve VL to nejsou typy (objekt nebo subjekt práva taky nejde nastavit)_
* upravit generování zdroje, aby pro daný typ zobrazoval správný zdroj
                     _- zdroj v žádném případě není generován, ani nemá typ. Zdroj je string, kterým autor pojmu specifikuje, odkud se vzala definice. Přiznám se, že netuším, jaký výsledek tady očekáváte._
* doplnit generování definice (a rozlišovat dle typu)
                    _- zase jako nahoře - definice se ani negeneruje, ani nemá typ._

Mohl byste upřesnit vaše očekávání, ideálně na konkrétních příkladech? Zbytek by neměl být problém.

**Comment by trusinas** [comment]
Metodikou myslím C2V11 - [Metodika definice údajů vedených v agendě](https://data.gov.cz/kodi/v%C3%BDstupy/C2V11.pdf)
### nezohledňuje se číselník dle metodiky
Podle metodiky (Odvození evidence údajů agendy, bod 5) se v RPP bude typ objektu, který je specializací číselníku, evidovat jako údaj objektu/subjektu. Toto aktuálně není implementováno.
Případně je možné, že jsem použil špatný objekt číselník, a proto export nefungoval. Proto jsem psal žádost o upřesnění.
**Pokud je implementace náročná, můžeme to (zatím?) přeskočit.**

### je nutné dořešit, jak se bude přavádět událost, pokud má vlastnosti
Podle metodiky (Odvození evidence údajů agendy, bod 4) bude událost evidována jako údaj. Tak se export aktuálně nechová.
Nicméně Martin Nečaský potvrdil, že typ události s více vlastnostmi bude v RPP skutečně (navzdory metodice) jako nový objekt.
**Ponechal bych stávající implementaci.**

### Nelze otestovat export pro typ
Toto je častým předmětem dotazů. Pokud se v metodice uvádí, že existují typy fáze a činnost, ale ve VL tomu tak není, uživatel se na to oprávněně ptá.
**Typy potřebujeme sjednotit (úpravou metodiky nebo VL).**

### upravit generování zdroje, aby pro daný typ zobrazoval správný zdroj
Používám pojmy z metodiky, a proto asi došlo ke zmatení.
V př. exportu do CSV se z VL exportuje atribut "Zdroj", který je přejmenován na "Právní předpis (vč. ustanovení)". Dle příkladu výše je nutné, aby se exportoval jak pro typy (z hlediska VL), tak i pro jejich vlastnosti.

### doplnit generování definice (a rozlišovat dle typu)
V př. exportu do CSV se z VL exportuje atribut "Definice", který je přejmenován na "Popis subjektu" a "Popis údaje". Dle příkladu výše je nutné, aby se exportoval jak pro typy (z hlediska VL), tak i pro jejich vlastnosti.

Pro generování Zdroje/ Právní předpis (vč. ustanovení) a Definice/Popis subjektu/údaje do CSV platí, že první řádek, který se týká objektu (resp. události), bude obsahovat Zdroj a Definici objektu, další řádky se budou týkat jeho vlastností, takže Zdroj a Definice budou obsahovat Zdroj a Definici dané vlastnosti.
Dokud jde o tentýž objekt, je nutné opakovat jeho název (1. sloupec), aby toto z tabulky bylo zřejmé.

Názorně jsem se to snažil ukázat na té tabulce výše. Radši přikládám i export diagramu.
![diagram_export](https://user-images.githubusercontent.com/42774229/233369660-48667689-0d4c-4084-9bc2-62c2de91ed92.png)

**Comment by bindeali** [comment]
V nejnovější testovací verzi to nyní vypadá takto: 
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/06e913e1-8252-4365-b50d-de3519dfd2aa)
Číselníky se tedy zohledňují jako typy objektu.

**Comment by bindeali** [comment]
## Shrnutí dosavadního stavu:

### Export pojmů
Obecně se držíme návrhu z [Šimonova komentáře](https://github.com/datagov-cz/sgov-assembly-line/issues/129#issuecomment-1508774846), společně s omezeními. 

Tento diagram:
![Snímek obrazovky 2023-08-01 144239](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/d83a1bfd-68f0-4846-b1d1-7918bd327df5)
tvoří tyto exporty:

![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/a3a02f80-cc2b-4a98-af36-81d2afd59c18)
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/4f5172b5-465f-48bc-a4df-240b9d344786)

Ale tento diagram:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/f89b412c-fe3f-4be4-bc89-787711dda7e5)
vytváří tento export:
- datum zničení
               - zničení auta
               - vlastnost vazby 1
               - vlastnost vazby 2
               - má vztažený prvek 1 zničení auta
               - má vztažený prvek 2 auto
_zničení auta_ je v tomto případě špatně a nemá být uvedena jako údaj (má být pouze u pojmu „auto“ a tam je). Nicméně v tomto případě to asi nemá smysl řešit, protože zde by reálně vazba s vlastnostmi neměla být.

### Změny v OG prezentaci:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/2435cb59-c4a0-4675-8829-a62454018e6c)
V OG uvažujeme o přidání modelování vztahů s vlastnostmi, které prozatím vypadá takto.
