### ISSUE TITLE
Nedokončený proces vytvoření pojmu

### ISSUE THREAD

**Issue by trusinas** [datagov-cz/sgov-assembly-line#141]
# Popis problému
Popište:
- při vytvoření nového pojmu v TermItu se pravděpodobně nedokončil proces zápisu pojmu
- TermIt zobrazuje 3 pojmy, ale v počtu jsou 4 a pojem díl půdního bloku opětovně nelze vytvořit
![obrazek](https://user-images.githubusercontent.com/42774229/230307532-2888fac9-b493-4639-82e2-f46bba9d1417.png)
https://slovník.gov.cz/modelujeme/v-n%C3%A1stroji/termit/#/vocabularies/1997?namespace=https://slovn%C3%ADk.gov.cz/legislativn%C3%AD/sb%C3%ADrka/252/

# Závažnost problému
3. zpomaluje mě to,

# Alternativy řešení
Pojem měl dlouho definici. Je aplikačně omezen počet znaků, aby pojem nešel vytvořit? A zobrazí se varovací hláška?

**Comment by MichalMed** [comment]
Vidím, že tam pojem už vytvořený je, takžepředpokládám, že vše funguje?
