### ISSUE TITLE
Zbytečné zobrazování názvů konektivních vazeb ve slovníku

### ISSUE THREAD

**Issue by Jiribuk11** [datagov-cz/sgov-assembly-line#148]
K jednotlivým konektorům v Ortographu jsou přiřazeny názvy konektivních vazeb - např. má přiřazen, existuje právě jeden,....
Tyto názvy se zobrazují ve slovníku - přijde mi to zbytečné. Nebo to má nějaký účel?  Přikládám obrázek:
![image](https://user-images.githubusercontent.com/130991526/232814384-41efb2ba-6876-409d-a7aa-8526248b1af8.png)

**Comment by MichalMed** [comment]
Vazby jsou stejně jako všechno ostatní především pojmy. Proto jsou uváděny v termitu.
