### ISSUE TITLE
V ortographu nelze zrušit chybně zapsanou vlastnost

### ISSUE THREAD

**Issue by Jiribuk11** [datagov-cz/sgov-assembly-line#150]
Postup:
1) K objektu v otographu přídám vlastnost
2) Přidám novou vlastnost, protože předchozí byla chybně specifikována
3) Chybí tlačítko mínus, jako kdysi pro zrušení přiřazené vlastnosti.  Pokud provedu delete, celý objekt  v diagramu zmizí.

**Comment by MichalMed** [comment]
Tlačítko mínus se objevuje pro každou vlastnost zvlášť po přejetí myší nad vlastností v seznamu v detailu pojmu.
[Screencast from 26.4.2023 23:04:08.webm](https://user-images.githubusercontent.com/3779672/234702300-9e42f6ab-7a2c-4cd6-8fe9-ced42695c4d3.webm)
