### ISSUE TITLE
Nevím jak připojit správně typ události

### ISSUE THREAD

**Issue by Jiribuk11** [datagov-cz/sgov-assembly-line#151]
Nevím, jak správně připojit událost aktualizace evidence půdy, kterou provádí Fond (slovník zák. 252/1997 Sb., diagram Evidence využití půdy)

Bukovský Jiří 724335077

**Comment by MichalMed** [comment]
V souladu s [metodikou](https://data.gov.cz/kodi/v%C3%BDstupy/C5V4.pdf) se událost připojuje pomocí vztahu "má účastníka". 

@bindeali - v současné verzi OG nevidím, můžeš to prosím zkontolovat?
