### ISSUE TITLE
Nerelevantní akce v hlavním menu Ontographeru se zobrazuji neintuitivně

### ISSUE THREAD

**Issue by blcham** [datagov-cz/sgov-assembly-line#160]
# Popis problému
Když si zobrazím slovník v Ontographeru např. [V-SGoV](https://xn--slovnk-7va.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?vocabulary=https://slovn%C3%ADk.gov.cz/ve%C5%99ejn%C3%BD-sektor/verze/89d04a64-508d-4f4b-bb6e-7840ac4e52dd), při prvním načítaní nefungují hlavní tlačítka:
"Switch to Full view"
"Validate"
"Export diagram .."

![image](https://github.com/datagov-cz/sgov-assembly-line/assets/3962237/f34480c2-b214-46f7-afdc-4dceffd7c283)

Zdá se že je to proto, že tyto tlačítka jsou nerelevantní, jelikož neni otevřen žádny konkrétní diagram a tedy tyto tlačítka nejde aplikovat. 

# Závažnost problému
- mojí práci to neovlivňuje, jelikož jsem po par minutách zjistil kde je problem, no myslím že to může být pro lidi velice neintuitivní a navíc řešení je docela jednoduché:

# Řešení
Akce, které nelze spustit by meli byt zašedivelé aby to uživatele nemátlo, že na ně může click-nout.

@bindeali

**Comment by MichalMed** [comment]
@bindeali alice prosím zaeviduj si to, až na tom začneme dělat, tak je to relevantní feedback

**Comment by bindeali** [comment]
@blcham Prosím otestuj řešení na https://deploy-preview-504--ontographer.netlify.app/

**Comment by blcham** [comment]
@bindeali napsal jsem to do pull requestu, v ontographeru nejsou zadne slovniky ...

**Comment by bindeali** [comment]
Zavírám s uzavřením https://github.com/datagov-cz/ontoGrapher/pull/504
