### ISSUE TITLE
Chybné chování kardinalit při zadávání

### ISSUE THREAD

**Issue by Jiribuk11** [datagov-cz/sgov-assembly-line#162]
Pokud vytvářím novou vazbu, nastavím konektor, ale kardinality jsou na obou koncích nastavit jen shodně.

**Comment by bindeali** [comment]
Dobrý den,

mohl byste prosím problém popsat podrobněji? Jaké jsou konkrétní kroky, po kterých vznikne? V jakém slovníku, nástroji a prostředí (slovník.gov.cz nebo slovník-test.dia.gov.cz) pracujete?

**Comment by Jiribuk11** [comment]
LPIS Mze – diagram erozní ohrožení – vazba viz obrázek

 

 

Ing. Jiří Bukovský
Oddělení registrů

 

Ministerstvo zemědělství
Těšnov 17, 110 00  Praha 1
Tel.: +420 221 812 710
GSM: +420 724 335 077
***@***.*** ***@***.***> 

www.eagri.cz <http://www.eagri.cz> 

 

 

 

 

 

 

Od: bindeali ***@***.***> 
Odesláno: úterý 22. srpna 2023 13:56
Komu: datagov-cz/sgov-assembly-line ***@***.***>
Kopie: Bukovský Jiří ***@***.***>; Author ***@***.***>
Předmět: Re: [datagov-cz/sgov-assembly-line] Chybné chování kardinalit při zadávání (Issue #162)

 

Dobrý den,

mohl byste prosím problém popsat podrobněji? Jaké jsou konkrétní kroky, po kterých vznikne? V jakém slovníku, nástroji a prostředí (slovník.gov.cz nebo slovník-test.dia.gov.cz) pracujete?

**Comment by bindeali** [comment]
Problém by měl být na produkčním prostředí vyřešen, prosím zkontrolujte a případně zavřete tento případ.

**Comment by bindeali** [comment]
Z důvodu neaktivity a dále toho, že tento bug není reportován nikým jiným, tento problém uzavírám.
