### ISSUE TITLE
Dev server vrati http error 502 pri pokuse otevrit slovnik v ontographeri/termite

### ISSUE THREAD

**Issue by blcham** [datagov-cz/sgov-assembly-line#163]
# Popis problému
V projekte, kliknutim na tlacitko "edit terms"/"edit relations" vrati 502 Bad Gateway.

# Závažnost problému
- je to vážný problém, jelikoz budeme chtit aktualni verzi nasadit na produkci

# Mozne duvody
Zrejme problem zpusobuje to ze byly aktualizovane docker images `docker-compose pull`, ktere vyuzivaji `latest` verze.

**Comment by bindeali** [comment]
Mohu potvrdit pro OG, Termit a také pro Keycloak admin console.

**Comment by blcham** [comment]
Problem se projevoval tak ze `/modelujeme/sluzby/auth-server/realms/assembly-line/protocol/openid-connect/auth` vracelo 502.

Chybu se podarilo opravit pomoci konfigurace vnejsiho nginx:
```
        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;
```

Souvisi s https://stackoverflow.com/questions/13894386/upstream-too-big-nginx-codeigniter

**Comment by bindeali** [comment]
Otevírání úprav v TermITu pořád nefunguje:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/966898da-a1c9-4e29-a022-9e08781e3517)
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/491156e2-3e9c-422e-ac74-dcf13b457e20)
Je to u serveru nebo u TermITa?

**Comment by blcham** [comment]
@bindeali To co popisujes je uz novy issue (o kterem jsme se bavili i na meetingu) ... Vytvoril jsem nato i issue #164  + issue v Teams.  Kdyz uz si delala screenshot, navrhuji aby si to pridala do issue #164 a tuto issue navrhuji uzavrit.
