### ISSUE TITLE
Dev instance neumi nacist Datový slovník OFN aktualit - slovník

### ISSUE THREAD

**Issue by blcham** [datagov-cz/sgov-assembly-line#164]
# Popis problému
Popište:
Pri vytvoreni noveho projektu a otevreni v TermItu "Datový slovník OFN aktualit - slovník" vraci error
```
No vocabulary found in context <https://slovník.gov.cz/datový/aktuality/verze/5c9221f3-04b9-457e-a9c4-4e2052d9b69c>
```

# Závažnost problému
- je to vážný problém avsak na dev instanci

**Comment by bindeali** [comment]
Otevírání úprav v TermITu pořád nefunguje:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/966898da-a1c9-4e29-a022-9e08781e3517)
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/56399637/491156e2-3e9c-422e-ac74-dcf13b457e20)
Je to u serveru nebo u TermITa?

**Comment by blcham** [comment]
Problem byl v datech. Reseni bylo odstraneni spatnych slovniku, databaze vsak byla ve stave kdy update dotazy nefungovali (?!mozna nedokonceny update ktery padl na nedostatek pameti)
