### ISSUE TITLE
Nelze exportovat slovník z Termit

### ISSUE THREAD

**Issue by trusinas** [datagov-cz/sgov-assembly-line#166]
# Popis problému
 - otevřít Termit
 - otevřít projekt _dokumentace 111/2009 Sb._ nebo _dokumentace A104_
 - exportovat do CSV nebo Excel

Export neproběhne. Nezobrazí se žádná chybová hláška. Export do Turtle proběhne. V př. jiného projektu export do Excelu proběhne.

# Závažnost problému
zpomaluje mě to,

**Comment by blcham** [comment]
@trusinas, uz by to melo fungovat.

**Comment by blcham** [comment]
@trusinas, opraveno, uz by to melo fungovat.
