### ISSUE TITLE
v OntoGrapheru občas nefunguje seznam pojmů slovníku

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#169]
# Popis problému
Otevřel jsem pro úpravy [tento slovník](https://slovník.gov.cz/legislativní/sbírka/106/1999) a OntoGrapher. Slovník obsahuje jeden pojem. Ten se ale v přehledu slovníků v levé části ukazuje pouze někdy. Navíc se u něj při přepínání mezi compact a full zobrazením zdánlivě náhodně zapíná jeho viditelnost (původně viditelný nebyl)

![og](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/068ef341-a5ac-4a87-b2ce-2eee9b53d308)

# Závažnost problému
2. je to vážný problém

**Comment by MichalMed** [comment]
V kompaktním módu se mezi pojmy typy vztahů a vlastností nezobrazují, je to tedy featura, nikoliv bug.

**Comment by bindeali** [comment]
Stejné, jako #175
