### ISSUE TITLE
Při vytváření diagramu v OG se nabídka slovníků nesmyslně schovává a vytváří další scrollbar

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#171]
# Popis problému
Při vytváření diagramu v OG se nabídka slovníků nesmyslně schovává a vytváří další scrollbar

![nový-diagram](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/41eb833d-3470-4df0-a69f-572f91f546d4)

# Závažnost problému
4. příliš mojí práci neovlivňuje.

**Comment by bindeali** [comment]
Mělo by být vyřešeno na PROD, prosím o kontrolu.

**Comment by jakubklimek** [comment]
Ano, opraveno.
