### ISSUE TITLE
Pravé tlačítko v OG pro přidání pojmu také otevírá kontextové menu prohlížeče

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#173]
# Popis problému
Když chci přidat pojem v OG pravým tlačítkem na canvas, otevře se krom dialogu také kontextové menu prohlížeče (Chrome 119).
![pravý-klik](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/09ce7781-a647-4db5-a108-72d72bfd2b57)

# Závažnost problému
3. zpomaluje mě to,

**Comment by MichalMed** [comment]
+1

**Comment by bindeali** [comment]
Mělo by být vyřešeno na PROD, prosím o kontrolu.

**Comment by jakubklimek** [comment]
Ano, funguje.
