### ISSUE TITLE
Pojmy vytvořené v TermItu mají FEL-UFO typy místo Z-SGoV typů

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#188]
# Popis problému
Popište:
- V TermItu vytvořím pojem a nastavím, že jde o typ objektu.
- Očekával bych, že uvidím, že se jedná o typ objektu, tj. `https://slovník.gov.cz/základní/pojem/typ-objektu` tak jako u jiných typů objektů.
- Místo toho se zobrazí (a dále i vypublikuje) typ `http://onto.fel.cvut.cz/ontologies/ufo/object-type`
- Žádný postprocessing se pak neděje a Dataspecer takový pojem nenajde.
![termit-ufo-typy](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/d1f830ee-f381-46a0-aa35-fafeb6a38901)

# Závažnost problému
- popište, jak závažný pro práci s výrobní linkou pro Vás problém je:
1. nemohu vůbec pracovat,

**Comment by bindeali** [comment]
Jak jsem psala v chatu, 

>Termit dělá typy podle onto.fel.cvut ontologie, která je ekvivalentní k zs-gov ontologii. OG to nemění, pokud na to nešaháš. Ale běžně OG používá zs-gov, takže stačí v OG odstranit typ a udělat ho znova.

Pokud nemáš nějaký návrh na změnu ze strany OG, tak navrhuji issue zavřít.

**Comment by jakubklimek** [comment]
No problem je ze TermIt je součástí VL. A je divne, ze každá součást přiřazuje jiné typy, navíc ty z TermIta neodpovídají popisu SSP a nedají se tak dobře použít v jiných nástrojích jako Dataspecer. Tedy je to problém konzistence VL jako takové.

**Comment by blcham** [comment]
@jakubklimek 

Dival jsem se do git repa termit-u a vypada to ze termit ma podporu pro zamenu UFO typu viz [PR](https://github.com/kbss-cvut/termit/pull/250)

Je potreba mu jenom dodat spravny [soubor s UFO typy](https://github.com/kbss-cvut/termit/blob/a95570e31e037ac8aa5a32b84cc8e79cfbfa8af0/src/main/resources/languages/types.ttl). 


Bohuzel ta zmena je stara 3 mesice, tak temer urcite to v TermIt-e z VL nebude.

**Comment by blcham** [comment]
Mozne reseni je modifikovat [Dockerfile](https://github.com/datagov-cz/termit/blob/main/Dockerfile) a pribalit to tam do resources.
