### ISSUE TITLE
Pokud v OG vytvořím pojem a smažu ho, nemohu vytvořit nový se stejným IRI

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#195]
# Popis problému
- Vytvořím pojem v OG
- Smažu ho
- Chci vytvořit pojem se stejným IRI - nelze.
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/6cb5427a-be7b-4460-bcef-04a90311d8d1)

Nepomůže ani reload/zavřít/otevřít OG.

V OG původní pojem sice vidět není, pokud ale slovník otevřu v TermItovi, tam vidět je.
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/d1274cef-4c02-45e8-9eab-8ee7ad61515f)

Když ho v TermItovi smažu, pak už můžu pojem se stejným IRI vytvořit v OG.

# Závažnost problému
3. zpomaluje mě to,

**Comment by bindeali** [comment]
Nedaří se mi potvrdit problém. Několikrát za sebou jsem smazala a vytvořila pojem se stejným IRI.

**Comment by jakubklimek** [comment]
Taky se mi to teď nepovedlo... Asi lze zavřít.
