### ISSUE TITLE
Badge s počtem publikací nefunguje?

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#200]
V kontrolním panelu je "badge" s počtem publikací. Nejsem si jist, jak přesně má fungovat, nicméně u mě stále svítí "0 publikací", i když jsem už řadu publikací vyrobil.
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/718827/f9d9cfd4-ae53-4561-a0e1-eefa89ac59b6)

**Comment by bindeali** [comment]
V kódu je natvrdo napsáno "0 publikací", viz https://github.com/datagov-cz/mission-control/blob/37182f2c0d0412ea2d1dc6894ce9df8740e982a9/src/components/user/UserProfiles.tsx#L64, beru si na starost.

**Comment by jakubklimek** [comment]
@bindeali byl bych pro to vyřešit smazáním
