### ISSUE TITLE
GitHub Action na SSP padá na Dev (AL) - Clear Cache

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/sgov-assembly-line#203]
# Popis problému
Po posledním merge padá GitHub action na SSP repo v kroku Dev (AL) - Clear Cache, viz https://github.com/datagov-cz/ssp/actions/runs/7903078794/job/21571084446 - z logu není jasné proč (HTTP 502).

# Závažnost problému
4. příliš mojí práci neovlivňuje.

**Comment by bindeali** [comment]
@blcham, prosím o řešení

**Comment by blcham** [comment]
Vyreseno.

V logu jsem toho moc nenasel, restart pomohol.
