### ISSUE TITLE
Validační služba nefunguje

### ISSUE THREAD

**Issue by bindeali** [datagov-cz/sgov-assembly-line#206]
Při volání služby přes OG se nedočkám odpovědi, visí to na (pending).

**Comment by blcham** [comment]
Prosim o pridani vic informaci, napriklad dle template issues pro bugy. Zkusil jsem jednu validaci, no ta mi funguje:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/3962237/7c58ee6f-f34c-45d9-98cc-49728423398d)

**Comment by bindeali** [comment]
Zkoušela jsem to znova (na TEST i PROD) a nakonec to funguje - asi tam byl nějaký dočasný problém. Pardon, zavírám.
