### ISSUE TITLE
Vlastnosti publikované třídy slovník-pro-agendu-a824-patenty-pojem:původce-jako-fyzická-osoba se nezobrazují v Ontographeri

### ISSUE THREAD

**Issue by blcham** [datagov-cz/sgov-assembly-line#207]
Reportovano od @bindeali :

>dnes sem začala modelovat ve VL novou agendu Užitné vzory. Myslela sem, že budu moc použít objekty/subjekty ze slovníku pro agendu patentů (které jsou pro všechny naše agendy a modely společné, např.: Přihlašovatel jako fyzická osoba atd.), ale když načtu objekt z tohoto slovníku, nejsou vidět jeho vlastnosti – vyexportovaný výpis pojmů pak vypadá takto (viz. obrázek níže). Je vhodné tyto objekty použít vzhledem k následnému přepisování pojmů do RPP Působnostní? Pokud bych objekty/subjekty musela vytvořit znovu, můžu použít stejné názvy objektů/subjektů a jejich vlastností, jako mám už v slovníku patentů, nebo tam budu muset přidat nějaké rozlišení, aby nebyly duplikovány?

# Popis problému
Nezobrazuji se vlastnosti objektu "Původce jako fyzická osoba" ([slovník-pro-agendu-a824-patenty-pojem:původce-jako-fyzická-osoba](https://slovník.gov.cz/generický/slovník-pro-agendu-a824-patenty/pojem/původce-jako-fyzická-osoba)) v Ontographer-u v [produkcni Vyrobni lince](https://xn--slovnk-7va.gov.cz/modelujeme/) (VL).

![image](https://github.com/datagov-cz/sgov-assembly-line/assets/3962237/f9a878a4-c7e6-418a-a62b-64eba65aaa94)

**Bohuzel nemam informace v jakem projektu to nastalo vramci VL.**

# Závažnost problému
- predpokladam, ze relevantni osoba nemuze vůbec pracovat,

**Comment by blcham** [comment]
@bindeali 

Neumel jsem reprodukovat problem, mne to funguje viz. projekt [MB-test](https://xn--slovnk-7va.gov.cz/modelujeme/projects/instance379348453):

![image](https://github.com/datagov-cz/sgov-assembly-line/assets/3962237/b2a082c0-313e-4113-841a-5ef6e5d3bf9e)

**Comment by bindeali** [comment]
Ale nefunguje to jako read-only pojem, viz e-mail:

> dnes sem začala modelovat ve VL novou agendu Užitné vzory. Myslela sem, že budu moc použít objekty/subjekty ze slovníku pro agendu patentů (které jsou pro všechny naše agendy a modely společné, např.: Přihlašovatel jako fyzická osoba atd.), ale když načtu objekt z tohoto slovníku, nejsou vidět jeho vlastnosti – vyexportovaný výpis pojmů pak vypadá takto (viz. obrázek níže). Je vhodné tyto objekty použít vzhledem k následnému přepisování pojmů do RPP Působnostní? Pokud bych objekty/subjekty musela vytvořit znovu, můžu použít stejné názvy objektů/subjektů a jejich vlastností, jako mám už v slovníku patentů, nebo tam budu muset přidat nějaké rozlišení, aby nebyly duplikovány?

To normálně ukazuje na OG problém, ale když to neumí číst ani ShowIT, tak je možná něco špatně v cache.

**Comment by bindeali** [comment]
Reupload cache nezafungoval.

**Comment by blcham** [comment]
Hmmm ... priznam se ze na read-only variantu jsem uz i zapomel ze mame :) 

@bindeali nehledal bych chybu "reupload cache" v ShowIt-u. Prosim muzes mi najit nejaky read-only koncept s atributy na kterem to v Ontographeru bude fungovat? Bohuzel se mi ho nepodarilo najit:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/3962237/e98d9f55-c17d-490b-8f19-39a7f3661f5a)

**Comment by blcham** [comment]
FYI, jeste jsem skontroloval ze v kanonickom slovniku na produkci nejake relevantni triply jsou:
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/3962237/542b46a1-d7d7-4a8a-a77e-5f2037a55608)

**Comment by bindeali** [comment]
OG budu muset ještě proklepnout, mám pocit, že tam je nějaký problém v nástroji. Podíváš se mezitím na ShowIT, prosím?

**Comment by bindeali** [comment]
Vyřešeno v OG pomocí https://github.com/datagov-cz/ontoGrapher/commit/d763a3f923f3b140928dee7abc3681f6e71738f2 a https://github.com/datagov-cz/ontoGrapher/commit/33cf2415cb7482d2fb7e0e64cf7d13e5014512af, zavírám.
