### ISSUE TITLE
Nelze editovat některé pojmy

### ISSUE THREAD

**Issue by marketaotipkova** [datagov-cz/sgov-assembly-line#210]
Pokud je to možné, pokuste se informaci o chybě rozepsat dle následující struktury, pomůžete nám ji rychleji identifikovat a opravit.

Nelze editovat pojmy - Představený - kód, Představený - označení
Popište:
- po rozkliknutí pojmu dostanu prázdnou obrazovku, kterou musím opustit uzavřením
- 
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/169747593/44399af3-e795-4738-ba9e-e9424c57b7de)

- v jakém nástroji jste pracovali - TermIt
- jaký pracovní prostor jste měli otevřený Slovník,
- na jaké obrazovce se problém projevil (např. detail pojmu Představený - kód, Představený - označení).
-
![image](https://github.com/datagov-cz/sgov-assembly-line/assets/169747593/08a7eedb-f065-4b84-9797-fd4345df5310)

# Závažnost problému
- popište, jak závažný pro práci s výrobní linkou pro Vás problém je:
2. je to vážný problém,

# Alternativy řešení
Pokud Vás napadají alternativní řešení, napište nám je.
Aspoň mi ty pojmy smažte a zkusím je vytvořit znovu.

Děkuji Markéta Otípková

**Comment by bindeali** [comment]
@blcham Vypadá to na problém mezi TermITem a validační službou, můžeš prosím mrknout, kde je chyba?
```
       Failed to load resource: the server responded with a status of 409 ()
09:35:52.757 react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'iri')
    at Function.value (ValidationResult.ts:45:48)
    at ValidationResults.tsx:24:25
    at Array.map (<anonymous>)
    at E (ValidationResults.tsx:23:20)
    at sa (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Pu (react-dom.production.min.js:250:347)
    at Au (react-dom.production.min.js:250:278)
    at Tu (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
ls @ react-dom.production.min.js:216
Show 1 more frame
Show less
09:35:52.757 react-dom.production.min.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'iri')
    at Function.value (ValidationResult.ts:45:48)
    at ValidationResults.tsx:24:25
    at Array.map (<anonymous>)
    at E (ValidationResults.tsx:23:20)
    at sa (react-dom.production.min.js:157:137)
    at Ks (react-dom.production.min.js:267:460)
    at Pu (react-dom.production.min.js:250:347)
    at Au (react-dom.production.min.js:250:278)
    at Tu (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
09:36:26.255  (3)(+0044272): Connector_Browser: onActivated for 
```
Celý log: [xn--slovnk-7va.gov.cz-1718005015196.log](https://github.com/user-attachments/files/15758285/xn--slovnk-7va.gov.cz-1718005015196.log)

**Comment by bindeali** [comment]
@marketaotipkova Dobrý den,

opravila jsem Vaše pojmy. Ověřte si prosím, že jsou u nich všechny Vámi zadané informace. V případě, že budou v budoucnu další problémy se systémem TermIT zkuste provést vaše změny v systému Ontographer.

**Comment by marketaotipkova** [comment]
Dobrý den,
atributy nelze editovat v Ontographeru. Další atributy, které nelze editovat jsou:
- datum narození
- ID služebního úřadu
- kód typu zástupce
- titul před jménem
- titul za jménem
Další dotaz je proč nevidím ve slovníku atribut "pohlaví" (možná jsem vytvářela v Ontographeru)
![image](https://github.com/user-attachments/assets/1f198cd0-b5ca-4a52-a796-037f4bfbf627)

Dále se chci zeptat proč se k typu objektu "státní zaměstnanec" nedotahují do slovníku atributy
![image](https://github.com/user-attachments/assets/4a41b2bf-919f-444a-afaf-05e76f524419)

**Comment by bindeali** [comment]
@marketaotipkova Dobrý den,

ve Výrobní lince je rozdíl mezi vlastnostmi a atributy. Vlastnosti - jméno, příjmení, titul, apod. jsou v TermITu evidovány ve výpisu pojmů slovníku a v Ontographeru v panelu daného pojmu, jak je vidět na Vašem snímku obrazovky. Vlastnosti jsou totiž také pojmy. Atributy v TermITu jsou něčím úplně jiným - váže se to k technickému popisu datové struktury slovníků jako takových a běžný uživatel Výrobní linky tyto atributy nepotřebuje využívat.

Na řešení problému v TermIT, kde nejde kliknout na nějaké pojmy, protože se jen dostanete k prázdné obrazovce, právě pracujeme. Mezitím jsme v Ontographeru přidali funkci editace vlastností (jejich definicí a synonym). K této editaci se dostanete při  kliknutí na Info ikonku, která se zobrazí při najetí myší na danou vlastnost daného pojmu, jak ukazuje obrázek níže.
<img width="268" alt="image" src="https://github.com/user-attachments/assets/fdb3fd9c-a7cd-4fbb-9069-f6fca2c5cc44">

**Comment by marketaotipkova** [comment]
Dobrý den,
kdy se dostanete k opravě pojmů? 
Přeji pěkný den
Markéta Otípková

**Comment by blcham** [comment]
@marketaotipkova 

> kdy se dostanete k opravě pojmů?

Prosim jen o ujasneni, ktere pojmy myslite. Napr. "představený - kód", "představený - označení" editovat lze. Dekuji.

**Comment by marketaotipkova** [comment]
Dobrý den,
pojmy jsou vyjmenované v požadavku výše
![image](https://github.com/user-attachments/assets/e9253feb-7875-4296-8e26-83d2b765fd4a)

Prosím o nějaký termín. 
Děkuji Markéta Otípková

**Comment by marketaotipkova** [comment]
Dobrý den, pořád to nefunguje. Můžu se zeptat, kdy se k tomu dostanete?
Děkuji

**Comment by bindeali** [comment]
Dobrý den,

Vámi nahlášené problémy jsem vyřešila a vlastnosti by Vám měly být znova dostupné. Problém nastal kvůli tomu, že atribut skos:hiddenLabel měl úplně stejnou hodnotu, jako jedno ze synonym pojmu - bohužel si s tím TermIT momentálně nedokáže poradit. Pro Vás to znamená, že byste při vytváření/úpravě pojmů v TermITu neměla používat sekci "Další atributy" (pokud danou sekci musíte používat, napište mi prosím, za jakým účelem - podle toho mohu případně nabídnout jiné řešení).

Omlouvám se za prodlevu v řešení tohoto problému, v případě dalších problémů nás neváhejte kontaktovat.
